import type { Metadata } from 'next';
import ClientLayout from './home/client-layout';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

export const metadata: Metadata = {
	title: 'Camnect',
	description: 'Generated by create next app',
	icons: '/assets/images/logo.png',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return <ClientLayout>{children}</ClientLayout>;
}
